### ISSUE TITLE
Questions about the Rainbow / PPO baselines

### ISSUE THREAD

**Issue by seungjaeryanlee** [Unity-Technologies/obstacle-tower-env#17]
Hello! I had a few questions about the experiments specified in the paper, and thought this would be the best place to ask.

1. Will the baseline code be available? If not, will the hyperparameters be available?
2. What equipment was used to train Rainbow / PPO? (Number of CPU, Type of GPU, etc.)
3. How long did the training take for 20M timesteps?

Thank you! I am very excited for the upcoming challenge 🚀

**Comment by awjuliani** [comment]
Hi @seungjaeryanlee,

These are good questions. We plan to release the baseline code we used so that participants in the challenge can use it as a jumping off point for their own experimentation. We used GCP a cloud instance with a GPU. It is the equivalent of an AWS P2 instance, if you are familiar with those. Training to 20 million steps took about 24 hours on this machine, given that we were running 50 instances of Obstacle Tower in parallel during training.

**Comment by seungjaeryanlee** [comment]
Thank you for the fast reply!

In case anyone who stumbles upon this issue is curious, these are the specs of the [AWS p2.xlarge instance](https://aws.amazon.com/ec2/instance-types/p2/):

```
1  NVIDIA K80 GPU
4  vCPU
61 GiB of RAM
```
