### ISSUE TITLE
Inconsistent distance for same moving commands.

### ISSUE THREAD

**Issue by mortido** [Unity-Technologies/obstacle-tower-env#20]
I've tried the following code and it plots images with different distance to a next door.
OS: Windows 10.

```
for i in range(10):
    env.seed(8)
    env.floor(1)
    obs = env.reset()

    for _ in range(20):
        obs, reward, done, info = env.step([1, 0, 0 ,0])

    plt.figure(figsize=(3,3))
    plt.imshow(obs[0])
    plt.show()
```

**Comment by seungjaeryanlee** [comment]
That's interesting! I also get slightly different images. (Ubuntu 16.04)

```python
plt.figure(figsize=(14, 6))
for i in range(10):
    env.seed(8)
    env.floor(1)
    obs = env.reset()

    for _ in range(20):
        obs, _, _, _ = env.step([1, 0, 0 ,0])

    plt.subplot(2, 5, i+1)
    plt.imshow(obs[0])
plt.show()
```


![yes](https://user-images.githubusercontent.com/6107926/52094180-85048700-2601-11e9-900e-317b06be3d1d.png)

I do get the same images when I check the observation immediately after reset:

```python
plt.figure(figsize=(14, 6))
for i in range(10):
    env.seed(8)
    env.floor(1)
    obs = env.reset()

    plt.subplot(2, 5, i+1)
    plt.imshow(obs[0])
plt.show()
```

![no_obs](https://user-images.githubusercontent.com/6107926/52094192-8cc42b80-2601-11e9-9650-f090506fc4e8.png)

**Comment by mortido** [comment]
BTW it works fine if recreate environment every time.
```
env = None
plt.figure(figsize=(14, 6))
for i in range(10):
    if env is not None:
        env.close()
    env = ObstacleTowerEnv('./ObstacleTower/obstacletower', retro=False)
    
    env.seed(8)
    env.floor(1)
    obs = env.reset()
    
    for _ in range(20):
        obs, _, _, _ = env.step([1, 0, 0 ,0])

    plt.subplot(2, 5, i+1)
    plt.imshow(obs[0])
plt.show()
```

**Comment by awjuliani** [comment]
Hi @mortido and @seungjaeryanlee 

Thanks to both of you for doing this investigation. I have been able to reproduce similar results myself. Especially your recent post @mortido leads me to believe this inconsistency is due to some aspect of the environment not being completely reset on reset. I will look into this and make sure it is resolved before the launch of the contest on Feb 11.

**Comment by awjuliani** [comment]
HI @mortido,

This level of small inconsistency is to be expected, and part of the environment. The simulation at the physics level is non-deterministic. We believe that this is actually a positive for the generalization aspect of the challenge. 

For the issues between resets, we have addressed this in an internal build, and plan to release a new build to the public prior to the start of the contest on Feb 11.

**Comment by kwea123** [comment]
Is this really a bug, or only a small inconsistency?
As @seungjaeryanlee suggests, the environment is probably the same after reset, and I suspect that the inconsistency is due to the door. Sometimes the door opens slowly, which causes the agent to be blocked at the door, so the results for moving forward 20 steps (or any sequence that crosses a door) are different. So this might be expected?

Can you confirm that the problem is at the door? @mortido @seungjaeryanlee
Thanks.

**Comment by awjuliani** [comment]
Hi all,

We just pushed a new release and binary (v1.1). This includes a fix for resetting the character animator between floors and resets. This should result in much more reproducible behavior between floors. It still won't be 100% due to inherent indeterminism in the Unity physics, but it is no longer nearly as extreme as shown above, and we believe within an acceptable range.
