### ISSUE TITLE
Time and hardware questions on your paper

### ISSUE THREAD

**Issue by MarcoMeter** [Unity-Technologies/obstacle-tower-env#49]
Hi @awjuliani 

on your paper, you trained PPO for 20 Mio and Rainbow DQN for 10 Mio steps. How long did it take in real-time and what hardware did you utilize?

And what time scale is used?

**Comment by awjuliani** [comment]
Hi @MarcoMeter 

The 20 million PPO run was done on an AWS P2 instance, and took about 24 hours. The Rainbow was done on a GCP instance w/ a GPU, and took about 48 hours. Because the Dopamine version of Rainbow is not parallelized, it takes longer to collect frames.

We run the Obstacle Tower at 15x timescale.

**Comment by MarcoMeter** [comment]
Thanks for the info!
